project:
  type: website
  output-dir: docs

website:
  title: "M244 Project"
  navbar:
    left:
      - href: EDAupdate.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



